-- Phase 1: Database & RLS
-- Strict RLS implementation: Every table defaults to denying access.
-- The service_role bypasses RLS automatically, giving the backend full access.

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Profiles Policy: Users can only read and update their own profile.
CREATE POLICY "Users can view own profile" 
    ON public.profiles FOR SELECT 
    USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" 
    ON public.profiles FOR UPDATE 
    USING (auth.uid() = id);

-- 2. Subscriptions Table
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    razorpay_payment_id TEXT UNIQUE,
    status TEXT NOT NULL CHECK (status IN ('active', 'expired', 'canceled')),
    valid_until TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Subscriptions Policy: Users can only view their own subscription status.
-- Writes/Updates are handled exclusively by the service_role (via webhooks).
CREATE POLICY "Users can view own subscriptions" 
    ON public.subscriptions FOR SELECT 
    USING (auth.uid() = profile_id);


-- 3. Chapters Table
CREATE TABLE IF NOT EXISTS public.chapters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    order_index INTEGER NOT NULL,
    is_published BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;

-- Chapters Policy: Anyone authenticated can view published chapters.
CREATE POLICY "Authenticated users can view published chapters" 
    ON public.chapters FOR SELECT 
    USING (auth.role() = 'authenticated' AND is_published = true);


-- 4. Media Table (For R2 assets, PDFs, images)
CREATE TABLE IF NOT EXISTS public.media (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chapter_id UUID REFERENCES public.chapters(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    r2_object_key TEXT NOT NULL, -- Stored securely, pre-signed URL generated by backend
    media_type TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;

-- Media Policy: Users can view metadata of media if they are authenticated.
-- Note: The actual file access is gated by the backend issuing a 60s AWS SigV4 URL.
CREATE POLICY "Authenticated users can view media metadata" 
    ON public.media FOR SELECT 
    USING (auth.role() = 'authenticated');


-- 5. Youtubes Table
-- CRITICAL SECURITY: Sealed off from all client roles; only service_role has access.
CREATE TABLE IF NOT EXISTS public.youtubes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chapter_id UUID REFERENCES public.chapters(id) ON DELETE CASCADE NOT NULL,
    youtube_video_id TEXT NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.youtubes ENABLE ROW LEVEL SECURITY;
-- Deliberately NO policies created for 'youtubes' table.
-- By default, RLS blocks all client access (anon and authenticated).
-- The Vercel API backend (using SUPABASE_SERVICE_ROLE_KEY) automatically bypasses this.


-- 6. Questions Table (For the Test Engine)
CREATE TABLE IF NOT EXISTS public.questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chapter_id UUID REFERENCES public.chapters(id) ON DELETE CASCADE NOT NULL,
    prompt TEXT NOT NULL,
    options JSONB NOT NULL, -- e.g., ["A", "B", "C", "D"]
    correct_answer TEXT NOT NULL, -- Never exposed to client
    difficulty_level INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

-- Questions Policy: NONE.
-- Tests are generated server-side. The client NEVER queries this table directly.
-- The server will query it, scrub the 'correct_answer' field, and send to client.
-- Therefore, we leave it fully sealed.
